# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getEigen <- function(M) {
    .Call(`_CloudGeometry_getEigen`, M)
}

geometricFeaturesCalculate <- function(x, ids, progbar) {
    .Call(`_CloudGeometry_geometricFeaturesCalculate`, x, ids, progbar)
}

