# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nnEigen <- function(x, radius = 1.0, varRadius = FALSE, progress = TRUE, verbose = FALSE, threads = 0L) {
    .Call(`_CloudGeometry_nnEigen`, x, radius, varRadius, progress, verbose, threads)
}

